# Generated by Django 4.0.4 on 2022-05-10 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(null=True, unique=True)),
                ('is_people', models.BooleanField(default=True)),
                ('people', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=100, null=True)),
                ('relative_name', models.CharField(max_length=100, null=True)),
                ('relative_type', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardin', 'Guardin'), ('Husband', 'Husband'), ('Wife', 'Wife')], max_length=100, null=True)),
                ('proof_type', models.CharField(choices=[('AADHAR CARD', 'AADHAR CARD'), ('Income Tax(PAN) Card', 'Income Tax(PAN) Card'), ('Voter Card', 'Voter Card'), ('Driving License', 'Driving License'), ('Passport', 'Passport'), ('Ration Card', 'Ration Card')], max_length=100, null=True)),
                ('proof_number', models.CharField(max_length=100, null=True)),
                ('house_name', models.CharField(max_length=100, null=True)),
                ('house_number', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('locality', models.CharField(max_length=100, null=True)),
                ('pin_code', models.IntegerField(null=True)),
                ('village', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('police_district', models.CharField(max_length=100, null=True)),
                ('police_station', models.CharField(max_length=100, null=True)),
                ('people', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
        ),
    ]
