# Generated by Django 4.0.4 on 2022-05-13 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_nature', models.CharField(choices=[('Against Public', 'Against Public'), ('Against Organization', 'Against Organization'), ('Against Police Officer', 'Against Police Officer'), ('Against Publice Servent', 'Against Publice Servent'), ('Wild Life Case', 'Wild Life Case'), ('Against Department', 'Against Department'), ('CYBER CRIME', 'CYBER CRIME')], max_length=150, null=True)),
                ('incident_place', models.CharField(max_length=150, null=True)),
                ('police_district', models.CharField(max_length=150, null=True)),
                ('police_place', models.CharField(max_length=150, null=True)),
                ('incident_date', models.DateTimeField(null=True)),
                ('file_discription', models.CharField(max_length=150, null=True)),
                ('file_upload', models.FileField(null=True, upload_to='media')),
                ('compalaint_description', models.TextField(null=True)),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.people')),
            ],
        ),
    ]
