# Generated by Django 4.0.4 on 2022-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_complaintregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintregistration',
            name='case_status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('FIR Registred', 'FIR Registred'), ('Disposed', 'Disposed')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='complaintregistration',
            name='complaint_status',
            field=models.CharField(choices=[('Registred', 'Registred'), ('Opened', 'Opened'), ('Closed', 'Closed')], default='Registred', max_length=150, null=True),
        ),
    ]
