# Generated by Django 4.0.4 on 2022-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_complaintregistration_case_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintregistration',
            name='ref_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
