# Generated by Django 4.0.4 on 2022-05-16 15:16

from django.db import migrations, models
import people.utils


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_complaintregistration_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='user_image',
            field=models.ImageField(null=True, upload_to=people.utils.PathAndRename('/images')),
        ),
        migrations.AlterField(
            model_name='complaintregistration',
            name='file_upload',
            field=models.FileField(null=True, upload_to=people.utils.PathAndRename('/images')),
        ),
    ]
