# Generated by Django 4.0.4 on 2022-05-19 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0005_officeaddress_office_district'),
        ('people', '0005_personalinfo_user_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept', models.BooleanField(default=False)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.complaintregistration')),
                ('lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.lawyer')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
        ),
    ]
