# Generated by Django 4.0.4 on 2022-06-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_assignedcomplaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='pinfo_complete',
            field=models.BooleanField(default=False),
        ),
    ]
