# Generated by Django 4.0.4 on 2022-06-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_personalinfo_pinfo_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintregistration',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
