# Generated by Django 4.0.4 on 2022-06-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_policedistrict_policestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policedistrict',
            name='police_district',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='police_station',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
