# Generated by Django 4.0.4 on 2022-06-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_policedistrict_police_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='complete_profile',
            field=models.BooleanField(default=False),
        ),
    ]
