# Generated by Django 4.0.4 on 2022-07-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_paymentrequest_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
