# Generated by Django 4.0.4 on 2022-05-16 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_complaintregistration_case_status_and_more'),
        ('police', '0002_police_police'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=150, null=True)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.complaintregistration')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='police.police')),
            ],
        ),
    ]
