# Generated by Django 4.0.4 on 2022-05-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0004_alter_addnote_options_addnote_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addnote',
            options={'ordering': ('-created',)},
        ),
    ]
