# Generated by Django 4.0.4 on 2022-06-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0005_alter_addnote_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='phone',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
