# Generated by Django 4.0.4 on 2022-06-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0006_alter_police_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnote',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
