# Generated by Django 4.0.4 on 2022-05-11 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(null=True, unique=True)),
                ('lawyer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=150, null=True)),
                ('office_address', models.CharField(max_length=150, null=True)),
                ('office_state', models.CharField(max_length=150, null=True)),
                ('office_city', models.CharField(max_length=150, null=True)),
                ('consulten_fee', models.IntegerField(null=True)),
                ('office', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.lawyer')),
            ],
        ),
        migrations.CreateModel(
            name='lawyerPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=50, null=True)),
                ('degree', models.CharField(max_length=200, null=True)),
                ('area_practice', models.CharField(max_length=200, null=True)),
                ('language', models.CharField(max_length=150, null=True)),
                ('experience', models.CharField(max_length=50, null=True)),
                ('court', models.CharField(max_length=150, null=True)),
                ('bar_name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
                ('file_cv', models.FileField(null=True, upload_to='media')),
                ('lawyer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lawyer.lawyer')),
            ],
        ),
    ]
