# Generated by Django 4.0.4 on 2022-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='is_hire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='is_lawyer',
            field=models.BooleanField(default=True),
        ),
    ]
