# Generated by Django 4.0.4 on 2022-05-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0002_lawyer_is_hire_lawyer_is_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='enrollment_number',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
