# Generated by Django 4.0.4 on 2022-05-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0004_lawyer_lawyer_image_alter_lawyerpersonalinfo_file_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeaddress',
            name='office_district',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
