# Generated by Django 4.0.4 on 2022-07-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0006_paymentrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
    ]
